<?xml version="1.0"?><package format="3"><name>vehicle_control</name><version>0.1.0</version><description>PID lane controller</description><maintainer email="juwnoo@example.com">juwnoo</maintainer><license>Apache-2.0</license><buildtool_depend>ament_python</buildtool_depend><depend>rclpy</depend><depend>geometry_msgs</depend><depend>std_msgs</depend><export><build_type>ament_python</build_type></export></package>
